## WARNING: DEMO ONLY, WILL NOT WORK IN THIS REPO

name: Docker Image CD

on:
  workflow_run:
   workflows: ["CI"]
   types:
    - completed
  workflow_dispatch:

env:
  WORKING_DIRECTORY: 06DevOps/PokemonStorageSystem

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: 06DevOps/PokemonStorageSystem
        file: 06DevOps/PokemonStorageSystem/dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pokestorage:${{github.sha}}
  deploy:
    
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Azure WebApp Deployment
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: pokestoragedocker 
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          publish-profile: ${{secrets.DOCKER_AZURE_PUBLISH_PROFILE}}
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          images: ${{ secrets.DOCKERHUB_USERNAME }}/pokestorage:${{github.sha}}